2015-05-19 11:05:05,565 15670 INFO ? openerp: OpenERP version 7.0
2015-05-19 11:05:05,566 15670 INFO ? openerp: addons paths: /opt/odoo/ant-dev/addons
2015-05-19 11:05:05,566 15670 INFO ? openerp: database hostname: localhost
2015-05-19 11:05:05,567 15670 INFO ? openerp: database port: 5432
2015-05-19 11:05:05,567 15670 INFO ? openerp: database user: odoo
2015-05-19 11:05:07,448 15670 INFO ? openerp.addons.google_docs.google_docs: GData lib version `%s GData-Python/2.0.17` detected
2015-05-19 11:05:08,500 15670 INFO ? openerp.service.wsgi_server: HTTP service (werkzeug) running on 0.0.0.0:8069
2015-05-19 11:05:08,503 15670 INFO ? openerp: OpenERP server is running, waiting for connections...
2015-05-19 11:05:36,307 15670 INFO ant1 openerp.modules.loading: loading 1 modules...
2015-05-19 11:05:36,508 15670 INFO ant1 openerp.modules.loading: loading 33 modules...
2015-05-19 11:05:37,282 15670 INFO ant1 openerp.modules.loading: Modules loaded.
2015-05-19 11:05:37,338 15670 INFO ant1 werkzeug: 127.0.0.1 - - [19/May/2015 11:05:37] "POST /web/action/load HTTP/1.1" 200 -
2015-05-19 11:05:39,409 15670 ERROR ant1 openerp.service.web_services: Exception: 
Traceback (most recent call last):
  File "/opt/odoo/ant-dev/openerp/service/web_services.py", line 718, in go
    (result, format) = obj.create(cr, uid, ids, datas, context)
  File "/opt/odoo/ant-dev/openerp/report/interface.py", line 94, in create
    pdf = create_doc(rml, title=self.title)
  File "/opt/odoo/ant-dev/openerp/report/interface.py", line 206, in create_pdf
    obj.render()
  File "/opt/odoo/ant-dev/openerp/report/render/render.py", line 59, in render
    self._result = self._render()
  File "/opt/odoo/ant-dev/openerp/report/render/rml.py", line 41, in _render
    return rml2pdf.parseNode(self.rml, self.localcontext, images=self.bin_datas, path=self.path,title=self.title)
  File "/opt/odoo/ant-dev/openerp/report/render/rml2pdf/trml2pdf.py", line 1044, in parseNode
    r.render(fp)
  File "/opt/odoo/ant-dev/openerp/report/render/rml2pdf/trml2pdf.py", line 331, in render
    pt_obj.render(el)
  File "/opt/odoo/ant-dev/openerp/report/render/rml2pdf/trml2pdf.py", line 1015, in render
    fis += r.render(node_story)
  File "/opt/odoo/ant-dev/openerp/report/render/rml2pdf/trml2pdf.py", line 906, in render
    return process_story(node_story)
  File "/opt/odoo/ant-dev/openerp/report/render/rml2pdf/trml2pdf.py", line 899, in process_story
    flow = self._flowable(node)
  File "/opt/odoo/ant-dev/openerp/report/render/rml2pdf/trml2pdf.py", line 822, in _flowable
    return  self._table(node)
  File "/opt/odoo/ant-dev/openerp/report/render/rml2pdf/trml2pdf.py", line 724, in _table
    assert length == len(node.get('colWidths').split(','))
AssertionError
2015-05-19 11:05:39,622 15670 ERROR ant1 openerp.netsvc: 
(<type 'exceptions.AssertionError'>, AssertionError(), <traceback object at 0xb2b329dc>)
Traceback (most recent call last):
  File "/opt/odoo/ant-dev/openerp/netsvc.py", line 300, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/odoo/ant-dev/openerp/service/web_services.py", line 660, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/ant-dev/openerp/service/web_services.py", line 766, in exp_report_get
    return self._check_report(report_id)
  File "/opt/odoo/ant-dev/openerp/service/web_services.py", line 744, in _check_report
    netsvc.abort_response(exc, exc.message, 'warning', exc.traceback)
  File "/opt/odoo/ant-dev/openerp/netsvc.py", line 75, in abort_response
    raise openerp.osv.osv.except_osv(description, details)
except_osv: ('', (<type 'exceptions.AssertionError'>, AssertionError(), <traceback object at 0xb2b329dc>))
2015-05-19 11:05:39,637 15670 INFO ant1 werkzeug: 127.0.0.1 - - [19/May/2015 11:05:39] "POST /web/report HTTP/1.1" 500 -
